import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner";

export default function Home() {
  function handleOnBannerBtnClick() {
    console.log("hey button!");
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.heroImage}>
          <Image src="/static/hero.png" width={456} height={456} />
        </div>
        <Banner
          buttonText="im a buttonn"
          handleOnClick={handleOnBannerBtnClick}
        />
      </main>
    </div>
  );
}
