import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner";
import Card from "../components/card";

export default function Home() {
  function handleOnBannerBtnClick() {
    console.log("hey button!");
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Banner
          buttonText="im a buttonn"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className="cards">
          <Card
            name="DarkHorse Coffee"
            imgUrl="/static/hero.png"
            href="/coffee-store/darkhorse"
          />
        </div>
      </main>
    </div>
  );
}
