import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner";
import Card from "../components/card";
import coffeeStoresData from "../data/coffee-stores.json";

export async function getStaticProps(context) {
  return {
    props: {
      coffeeStores: coffeeStoresData,
    },
  };
}

export default function Home(props) {
  function handleOnBannerBtnClick() {
    console.log("hey button!");
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Banner
          buttonText="im a buttonn"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className="heading">São Paulo</div>
        <div className="cards">
          {props.coffeeStores.length > 0 ? (
            props.coffeeStores.map((cs) => (
              <Card
                key={cs.id}
                name={cs.name}
                imgUrl={cs.imgUrl}
                href={`/coffee-store/${cs.id}`}
              />
            ))
          ) : (
            <h2>Sorry, but there are no Coffee Shops Nearby!</h2>
          )}
        </div>
      </main>
    </div>
  );
}
